{{- if (index .Values "mcp-servers").enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: toolhive-operator-manager-role-{{ .Release.Namespace }}
  labels:
    {{- include "rag.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - pods/log
  - pods/attach
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - apply
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
  - apply
- apiGroups:
  - toolhive.stacklok.dev
  resources:
  - mcpservers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - toolhive.stacklok.dev
  resources:
  - mcpservers/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - toolhive.stacklok.dev
  resources:
  - mcpservers/finalizers
  verbs:
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: toolhive-operator-manager-rolebinding-{{ .Release.Namespace }}
  labels:
    {{- include "rag.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: toolhive-operator-manager-role-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: toolhive-operator
  namespace: {{ .Release.Namespace }}
{{- end }}
