{{- if .Values.notebook.create }}
# This secret will be used by the rag-pipeline-notebook
---
apiVersion: v1
kind: Secret
metadata:
  name: rag-ingestion-pipeline-secret
  annotations: {}
  labels:
    opendatahub.io/dashboard: 'true'
stringData:
  SOURCE: S3
  EMBEDDING_MODEL: {{ .Values.notebook.embedding_model }}
  NAME:  {{ .Values.notebook.name }}
  VERSION:  "{{ .Values.notebook.version }}"
  ACCESS_KEY_ID: {{ .Values.minio.secret.user }}
  SECRET_ACCESS_KEY: {{ .Values.minio.secret.password }}
  ENDPOINT_URL:  "http://{{ .Values.minio.secret.host }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.minio.secret.port }}"
  BUCKET_NAME: {{ .Values.notebook.minio.bucket_name }}
  REGION: {{ .Values.notebook.minio.region }}
{{- end }}